// Generated by .NET Reflector from C:\Data\GitHub\WebSocket4Net\Reference\SuperSocket.ClientEngine\Net35\Debug\SuperSocket.ClientEngine.Core.dll
namespace SuperSocket.ClientEngine
{
    using System;
    using System.Runtime.CompilerServices;
    
    public class DataEventArgs : EventArgs
    {
        public byte[] Data { get; set; }
        
        public int Length { get; set; }
        
        public int Offset { get; set; }
    }
}
