name: build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        strategy:
          matrix:
            os:
            - ubuntu-latest
            - windows-latest
            - macos-latest
        runs-on: ${{matrix.os}}
        env:
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '9.0.x'
            - name: Build
              run: dotnet build -c Release
            - name: Test
              run: |
                cd test/WebSocket4Net.Tests
                dotnet test
            - uses: dotnet/nbgv@master
              id: nbgv
              if: runner.os == 'macOS'
            - name: Pack & push nuget packages to myget
              if: runner.os == 'macOS'
              run: |
                dotnet clean
                dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json
                dotnet pack -c Release -p:IncludeMobileTargetFramework=true -p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} -p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} -p:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }} -p:AssemblyFileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }} -p:AssemblyInformationalVersion=${{ steps.nbgv.outputs.AssemblyInformationalVersion }} /p:NoPackageAnalysis=true
                dotnet nuget push **/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/websocket4net/api/v3/index.json